#!/bin/bash
# Begin post_install_reboot

echo "This will safely shut down the system and reboot the"
echo "computer when nothing else will. Run this in a tty"
echo "console, not in an X Windows terminal."
echo
echo -n "Ready to proceed? (y/n) "
read REPLY
if [ "$REPLY" != "y" ] ; then
    read -p "Press a key to abort."
    exit 0
fi

# Check for root privileges...
if [ $EUID -ne 0 ]; then
   echo
   echo "Must be run as root."
   echo
   exit 1
fi

echo "Stopping system and kernel logging daemons."
kill -9 $(pidof klogd)
kill -9 $(pidof syslogd)

echo "Stopping the udev daemon..."
udevadm control --exit

echo "Sending all processes the TERM signal..."
pkill --inverse -s0,1 -TERM
sleep 5

echo "Sending all processes the KILL signal..."
pkill --inverse -s0,1 -KILL
sleep 5

echo "Unmounting all non-virtual filesystems..."
umount -a -d -r -t notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts
sleep 1

echo "Re-mounting root filesystem ro..."
mount -o remount,ro /
sleep 1

echo "Rebooting now..."
echo b > /proc/sysrq-trigger

# End post_install_reboot
