#!/bin/sh

# Linux From Scratch Runit Stage 2 Bootscript.
# Copyright 2014 James Powell, Keith Hedger, and Stoat of LinuxQuestions.
# Work derived from VoidLinux and Ignite and adapted for LFS.

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# Setup first tty as unicode again, stage1 does not work correctly for tty1.
unicode_start

# Try and detect if the current runlevel directory has been created yet. It
# should exist as a symlink to the current selected runlevel via runsvchdir.
# If the symlinked service directories are not found, they will be created.
if [ ! -d /etc/runit/runsvdir/current ]; then
   pushd /etc/runit/runsvdir
   ln -s multi current
   popd
fi

# Let runsvchdir select the default runlevel
runsvchdir multi >/dev/null

# If any legacy scripts exist in the system, use rc.local to start them
# using this syntax:
# if [ -<trigger> "</path/to/script>"; then
#     </path/to/script> -<arguments>
# fi
# You can create a directory named /etc/rc.d for this purpose and store
# and load them from there.
[ -x /etc/rc.local ] && /etc/rc.local

# Start all services detected in the current runlevel directory.
exec env - PATH=$PATH \
runsvdir /etc/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'

