#!/bin/sh

# Linux From Scratch Runit Ctrl+Alt+Del handling script.
# Copyright 2014 James Powell, Keith Hedger, and Stoat of LinuxQuestions.
# Work derived from VoidLinux and Ignite and adapted for LFS.

PATH=/bin:/sbin:/usr/bin:/usr/sbin
MSG="System is going down..."

# We check for this file in stage3 to halt or reboot
touch /etc/runit/reboot

# Proceed with shutdown process
#touch /etc/runit/stopit
touch /etc/runit/reboot
chmod 100 /etc/runit/reboot && echo "$MSG" | wall
#chmod 100 /etc/runit/reboot && echo "$MSG" | wall
