#!/bin/sh

# Linux From Scratch Runit Ctrl+Alt+Del handling script.
# Copyright 2014 James Powell, Keith Hedger, and Stoat of LinuxQuestions.
# Work derived from VoidLinux and Ignite and adapted for LFS.

PATH=/bin:/sbin:/usr/bin:/usr/sbin
MSG="System is going down in 10 seconds..."

# Uncomment to disable Ctrl+Alt+Del...
#echo Ctrl+Alt+Del is disabled. ; exit 0

touch /etc/runit/{reboot,stopit}

# Uncomment for Ctrl+Alt+Del to reboot...
chmod 100 /etc/runit/{reboot,stopit}

# Uncomment for Ctrl+Alt_Del to poweroff...
#chmod 100 /etc/runit/stopit && chmod 0 /etc/runit/reboot

echo "$MSG" | wall
/bin/sleep 10