#!/bin/sh

# This service will update the cache of the machine in one of two ways, either
# continuously, or upon startup of the daemon. It is recommended that you use
# the default setup to run this daemon.

exec ldconfig
exec update-desktop-database /usr/share/applications
exec gdk-pixbuf-query-loaders --update-cache
exec glib-compile-schemas /usr/share/glib-2.0/schemas
exec pango-querymodules --update-cache
exec gtk-query-immodules-3.0 --update-cache

# If you would like to run the daemon continually comment out the pause applet
# execution. By default pause is enabled.

exec /usr/bin/pause