#!/bin/sh
# Begin bind service run file
MEM="`head -1 ./env/MEM`"
CHROOT="`head -1 ./env/CHROOT`"
exec softlimit -m "${MEM}" \
  named -u bind -t "${CHROOT}" -g 2>&1
# End of bind run service file
